### PR TITLE
Fix ndjson streaming for sumologic

### PR DESCRIPTION
**Pull request by fyockm**
# ✏️ Changes
Properly support the new line separator that SumoLogic uses by default to separate entries (https://help.sumologic.com/Send-Data/Sources/02Sources-for-Hosted-Collectors/HTTP-Source).

# 🔗 References
Zendesk: https://auth0.zendesk.com/agent/tickets/37939

# 🎯 Testing

✅ This has been tested locally
✅ This has been tested in a webtask
✅This change has unit test coverage
✅This change has been acceptance tested
✅This change has been manually smoke tested

# 🚀 Deployment
🚫 This change can support multiple releases of the code serving traffic at the same time
✅ This can be deployed any time because it has no prerequisites.

# 🎡 Rollout

✅ The change will be available to the complete environment at once
🚫 The change is behind a feature flag and will go through a percentage based rollout process
🚫 The change is behind a flag and customers will opt-in to the change

In order to verify that the deployment was successful we will update the extensions via a test tenant and perform smoke tests to ensure proper execution.

# 🔥 Rollback If

- the smoke test fails
- we receive a customer ticket indicating we broke the extension

## 📄 Procedure

A code revert+redeploy can be done to revert the change.

# 🖥 Appliance

✅ This change is compatible with the appliance.

### CODE REVIEW

**Comment by auth0extensions** [comment]
MD5: 1c9e99e48a495fe81d388fdb4900e59f

# NSP - Security Report

_This is an automated security audit of this project. Please do not modify its contents_

Vulnerabilities found: **28**
Affected Modules: **hoek, hoek, hoek, hoek, hoek, superagent, superagent, superagent, superagent, superagent, mime, mime, mime, mime, mime, mime, superagent, superagent, superagent, lodash, superagent, superagent, uglify-js, uglify-js, constantinople, lodash, lodash, node-uuid**
Summary:

- Prototype pollution attack
- Prototype pollution attack
- Prototype pollution attack
- Prototype pollution attack
- Prototype pollution attack
- Large gzip Denial of Service
- Large gzip Denial of Service
- Large gzip Denial of Service
- Large gzip Denial of Service
- Large gzip Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Large gzip Denial of Service
- Large gzip Denial of Service
- Large gzip Denial of Service
- Prototype Pollution
- Large gzip Denial of Service
- Large gzip Denial of Service
- Incorrect Handling of Non-Boolean Comparisons During Minification
- Regular Expression Denial of Service
- Sandbox Bypass Leading to Arbitrary Code Execution
- Prototype Pollution
- Prototype Pollution
- Insecure Entropy Source - Math.random()


## Detailed report
#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-extension-express-tools@1.1.7 > webtask-tools@3.2.1 > boom@2.10.1 > hoek@2.16.3**

---

#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-extension-tools@1.3.1 > jsonwebtoken@7.4.3 > joi@6.10.1 > hoek@2.16.3**

---

#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-log-extension-tools@1.3.6 > auth0-extension-tools@1.3.2 > webtask-tools@3.2.1 > boom@2.10.1 > hoek@2.16.3**

---

#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-logs-to-sumologic@2.0.8 > jsonwebtoken@7.4.3 > joi@6.10.1 > hoek@2.16.3**

---

#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-logs-to-sumologic@2.0.8 > webtask-tools@3.2.1 > boom@2.10.1 > hoek@2.16.3**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-extension-express-tools@1.1.7 > webtask-tools@3.2.1 > superagent@1.8.5**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-extension-tools@1.3.1 > webtask-tools@2.2.0 > superagent@1.8.5**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-log-extension-tools@1.3.6 > auth0-extension-tools@1.3.2 > webtask-tools@3.2.1 > superagent@1.8.5**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-oauth2-express@1.3.0 > superagent@1.8.5**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.8 > webtask-tools@3.2.1 > superagent@1.8.5**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-extension-express-tools@1.1.7 > webtask-tools@3.2.1 > superagent@1.8.5 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-extension-tools@1.3.1 > webtask-tools@2.2.0 > superagent@1.8.5 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-log-extension-tools@1.3.6 > superagent@1.2.0 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-oauth2-express@1.3.0 > superagent@1.8.5 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-logs-to-sumologic@2.0.8 > superagent@1.2.0 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-logs-to-sumologic@2.0.8 > webtask-tools@3.2.1 > superagent@1.8.5 > mime@1.3.4**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **2.3.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-extension-express-tools@1.1.7 > auth0-extension-tools@1.3.2 > superagent@2.3.0**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **2.3.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-extension-tools@1.3.1 > superagent@2.3.0**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **2.3.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-log-extension-tools@1.3.6 > auth0-extension-tools@1.3.2 > superagent@2.3.0**

---

#### Prototype Pollution

Affected Module: **lodash**
Installed version: **4.8.2**
Patched versions: **>=4.17.5**
Advisory: https://nodesecurity.io/advisories/577
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-log-extension-tools@1.3.6 > lodash@4.8.2**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.2.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-log-extension-tools@1.3.6 > superagent@1.2.0**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.2.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.8 > superagent@1.2.0**

---

#### Incorrect Handling of Non-Boolean Comparisons During Minification

Affected Module: **uglify-js**
Installed version: **2.2.5**
Patched versions: **>= 2.4.24**
Advisory: https://nodesecurity.io/advisories/39
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-oauth2-express@1.3.0 > jade@1.11.0 > transformers@2.1.0 > uglify-js@2.2.5**

---

#### Regular Expression Denial of Service

Affected Module: **uglify-js**
Installed version: **2.2.5**
Patched versions: **>=2.6.0**
Advisory: https://nodesecurity.io/advisories/48
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-oauth2-express@1.3.0 > jade@1.11.0 > transformers@2.1.0 > uglify-js@2.2.5**

---

#### Sandbox Bypass Leading to Arbitrary Code Execution

Affected Module: **constantinople**
Installed version: **3.0.2**
Patched versions: **>=3.1.1**
Advisory: https://nodesecurity.io/advisories/568
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-oauth2-express@1.3.0 > jade@1.11.0 > constantinople@3.0.2**

---

#### Prototype Pollution

Affected Module: **lodash**
Installed version: **3.10.1**
Patched versions: **>=4.17.5**
Advisory: https://nodesecurity.io/advisories/577
Path: **auth0-logs-to-sumologic@2.0.8 > auth0-oauth2-express@1.3.0 > auth0-api-jwt-rsa-validation@0.0.1 > lodash@3.10.1**

---

#### Prototype Pollution

Affected Module: **lodash**
Installed version: **3.10.1**
Patched versions: **>=4.17.5**
Advisory: https://nodesecurity.io/advisories/577
Path: **auth0-logs-to-sumologic@2.0.8 > lodash@3.10.1**

---

#### Insecure Entropy Source - Math.random()

Affected Module: **node-uuid**
Installed version: **1.4.3**
Patched versions: **>=1.4.4**
Advisory: https://nodesecurity.io/advisories/93
Path: **auth0-logs-to-sumologic@2.0.8 > node-uuid@1.4.3**

---

**Comment by FadyMak** [comment]
@fyockm The change LGTM - a quick question: would this affect existing customers that have the `Enable One Message Per Request` setting checked in the HTTP source config in SumoLogic and do *not* have `Enable Multiline Processing` checked?

Also, if we send out multiline log messages (whether we're doing it now or in the future or from a sandbox error) containing `\n` it might result in incorrectly parsed logs. Perhaps we should explicitly ask customers to include the Boundary Regex and specify it to be something more explicit `--a0-eol--`? (of course, that would be a breaking change)

**Comment by fyockm** [comment]
@FadyMak I think that's a documentation problem. Perhaps we should update our docs to specify the settings we expect - https://auth0.com/docs/extensions/sumologic

All previous versions of Sumologic (except for the broken `2.0.7`) sent Multiline Logs.

**Comment by FadyMak** [comment]
Sounds good, in that case LGTM 👍

**Pull request merged**
