### PR TITLE
Retry on API errors and maxRunTimeSeconds increase

### PR DESCRIPTION
**Pull request by zxan1285**
✏️ Changes
Updating `auth0-log-extension-tools` version, where `maxRunTimeSeconds` default value has been increased to 28 seconds and also implemented retry functionality for auth0 api errors.

🔗 References
Slack conversation: https://auth0.slack.com/archives/C9170558S/p1528229375000437

🎯 Testing
✅ This has been tested locally
✅ This has been tested in a webtask

### CODE REVIEW

**Comment by auth0extensions** [comment]
MD5: a396c59a96af3b36d364448c7b687fb1

# NSP - Security Report

_This is an automated security audit of this project. Please do not modify its contents_

Vulnerabilities found: **26**
Affected Modules: **hoek, hoek, hoek, hoek, hoek, superagent, superagent, superagent, superagent, superagent, mime, mime, mime, mime, mime, superagent, superagent, superagent, lodash, superagent, uglify-js, uglify-js, constantinople, lodash, lodash, node-uuid**
Summary:

- Prototype pollution attack
- Prototype pollution attack
- Prototype pollution attack
- Prototype pollution attack
- Prototype pollution attack
- Large gzip Denial of Service
- Large gzip Denial of Service
- Large gzip Denial of Service
- Large gzip Denial of Service
- Large gzip Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Regular Expression Denial of Service
- Large gzip Denial of Service
- Large gzip Denial of Service
- Large gzip Denial of Service
- Prototype Pollution
- Large gzip Denial of Service
- Incorrect Handling of Non-Boolean Comparisons During Minification
- Regular Expression Denial of Service
- Sandbox Bypass Leading to Arbitrary Code Execution
- Prototype Pollution
- Prototype Pollution
- Insecure Entropy Source - Math.random()


## Detailed report
#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-extension-express-tools@1.1.7 > webtask-tools@3.2.1 > boom@2.10.1 > hoek@2.16.3**

---

#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-extension-tools@1.3.1 > jsonwebtoken@7.4.3 > joi@6.10.1 > hoek@2.16.3**

---

#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-log-extension-tools@1.3.2 > auth0-extension-tools@1.3.1 > jsonwebtoken@7.4.3 > joi@6.10.1 > hoek@2.16.3**

---

#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-logs-to-sumologic@2.0.7 > jsonwebtoken@7.4.3 > joi@6.10.1 > hoek@2.16.3**

---

#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-logs-to-sumologic@2.0.7 > webtask-tools@3.2.1 > boom@2.10.1 > hoek@2.16.3**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-extension-express-tools@1.1.7 > webtask-tools@3.2.1 > superagent@1.8.5**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-extension-tools@1.3.1 > webtask-tools@2.2.0 > superagent@1.8.5**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-log-extension-tools@1.3.2 > auth0-extension-tools@1.3.1 > webtask-tools@2.2.0 > superagent@1.8.5**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-oauth2-express@1.3.0 > superagent@1.8.5**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.7 > webtask-tools@3.2.1 > superagent@1.8.5**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-extension-express-tools@1.1.7 > webtask-tools@3.2.1 > superagent@1.8.5 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-extension-tools@1.3.1 > webtask-tools@2.2.0 > superagent@1.8.5 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-log-extension-tools@1.3.2 > superagent@1.2.0 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-oauth2-express@1.3.0 > superagent@1.8.5 > mime@1.3.4**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-logs-to-sumologic@2.0.7 > webtask-tools@3.2.1 > superagent@1.8.5 > mime@1.3.4**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **2.3.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-extension-express-tools@1.1.7 > auth0-extension-tools@1.3.1 > superagent@2.3.0**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **2.3.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-extension-tools@1.3.1 > superagent@2.3.0**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **2.3.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-log-extension-tools@1.3.2 > auth0-extension-tools@1.3.1 > superagent@2.3.0**

---

#### Prototype Pollution

Affected Module: **lodash**
Installed version: **4.8.2**
Patched versions: **>=4.17.5**
Advisory: https://nodesecurity.io/advisories/577
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-log-extension-tools@1.3.2 > lodash@4.8.2**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.2.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-log-extension-tools@1.3.2 > superagent@1.2.0**

---

#### Incorrect Handling of Non-Boolean Comparisons During Minification

Affected Module: **uglify-js**
Installed version: **2.2.5**
Patched versions: **>= 2.4.24**
Advisory: https://nodesecurity.io/advisories/39
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-oauth2-express@1.3.0 > jade@1.11.0 > transformers@2.1.0 > uglify-js@2.2.5**

---

#### Regular Expression Denial of Service

Affected Module: **uglify-js**
Installed version: **2.2.5**
Patched versions: **>=2.6.0**
Advisory: https://nodesecurity.io/advisories/48
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-oauth2-express@1.3.0 > jade@1.11.0 > transformers@2.1.0 > uglify-js@2.2.5**

---

#### Sandbox Bypass Leading to Arbitrary Code Execution

Affected Module: **constantinople**
Installed version: **3.0.2**
Patched versions: **>=3.1.1**
Advisory: https://nodesecurity.io/advisories/568
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-oauth2-express@1.3.0 > jade@1.11.0 > constantinople@3.0.2**

---

#### Prototype Pollution

Affected Module: **lodash**
Installed version: **3.10.1**
Patched versions: **>=4.17.5**
Advisory: https://nodesecurity.io/advisories/577
Path: **auth0-logs-to-sumologic@2.0.7 > auth0-oauth2-express@1.3.0 > auth0-api-jwt-rsa-validation@0.0.1 > lodash@3.10.1**

---

#### Prototype Pollution

Affected Module: **lodash**
Installed version: **3.10.1**
Patched versions: **>=4.17.5**
Advisory: https://nodesecurity.io/advisories/577
Path: **auth0-logs-to-sumologic@2.0.7 > lodash@3.10.1**

---

#### Insecure Entropy Source - Math.random()

Affected Module: **node-uuid**
Installed version: **1.4.3**
Patched versions: **>=1.4.4**
Advisory: https://nodesecurity.io/advisories/93
Path: **auth0-logs-to-sumologic@2.0.7 > node-uuid@1.4.3**

---

**Comment by fyockm** [comment]
I think we need to remove this line: https://github.com/auth0-extensions/auth0-logs-to-sumologic/pull/21/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R29
or get `auth0-log-extension-tools@1.3.2` added to the webtask cluster

**Comment by zxan1285** [comment]
It is `auth0-extension-tools@1.3.1` in `externals, not auth0-**log**-extension-tools.
`auth0-log-extension-tools` was never added to the webtask.

**Comment by fyockm** [comment]
yes you're right. sorry for my confusion.

**Pull request closed without merging**
